### ISSUE TITLE
Add IEnumerable<string> ExceptNullOrEmpty / ExceptNullOrWhitespace / DistinctIgnoreCase 

### ISSUE THREAD

**Issue by gigi81** [soenneker/soenneker.extensions.enumerable.string#528]
Hello again @soenneker 

Here some extension methods I would suggest:

- ExceptNullOrEmpty
- ExceptNullOrWhitespace
- DistinctIgnoreCase

Not sure if the best word to use here would be `Except` or `Exclude`... or something else.

For example instead of:
```
arrayofString.Where(s => !string.IsNullOrEmpty(s))
```

```
arrayofString.ExceptNullOrEmpty()
```

**Comment by soenneker** [comment]
`RemoveNullOrEmpty`, `RemoveNullOrWhitespace`, `DistinctIgnoreCase` chosen.

Please feel free to submit PRs as well - thank you
